version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    networks:
      - app-network

  partner-service-api:
    build: ./partner-service-api
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  order-service-api:
    build: ./order-service-api
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge