version: '3.8'

services:
  postgres:
    build: ./infra/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network

  rabbitmq:
    build: ./infra/rabbitmq
    ports:
      - "5672:5672"     # Porta padrão do RabbitMQ
      - "15672:15672"   # Porta do painel de administração
    networks:
      - app-network

  partner-service-api:
    build: ./partner-service-api
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  order-service-api:
    build: ./order-service-api
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

  order-worker:
    build: ./order-worker
    ports:
      - "8083:8080"
    depends_on:
      - rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
