spring:
  application:
    name: partner-service-api
  datasource:
    url: jdbc:postgresql://postgres:5432/orders
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
